- hosts: localhost
  
  vars:
  - dock_key_url: https://download.docker.com/linux/ubuntu/gpg
  - dock_repo_url: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  
  tasks:
  
  - name: Install dependancies
    apt:
      name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: yes
      
  - name: Add Docker GPG apt key
    apt_key:
      url: "{{ dock_key_url }}"
      state: present
    become: yes
      
  - name: Add Docker repository
    apt_repository:
      repo: "{{ dock_repo_url }}"
      state: present
    become: yes
     
  - name: Install docker
    apt:
      name: docker-ce
      update_cache: yes
      state: present
    become: yes
       
      
